FROM python:3.9

# python environment
RUN python3 --version
RUN pip3 --version

# set the working directory 
WORKDIR  /usr/src/moss_example

# Installing python dependencies and libraries
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy files from the root directory to the working directory
COPY core/ /src/
RUN ls -la /src/*

# Running Python Application
CMD ["python3", "/src/load_data.py"]